#cloud-config
hostname: alpine-cloudinit
package_update: true
packages:
  - nano
write_files:
  - path: /etc/resolv.conf
    permissions: 0644
    owner: root
    content: |
      nameserver ns
system_info:
  default_user:
    name: bigred
    groups: users
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    plain_text_passwd: 'bigred'
    homedir: /home/bigred
    shell: /bin/bash
ssh_pwauth: True
# - bootcmd will run on every boot
#bootcmd:
#  - echo "hi bigred" > /home/bigred/test
